openapi: 3.0.0
info:
  title: Online Applications
  description:
  version: 1.0.0
servers:
  - url: https://localhost:3000/
components:
securitySchemes:
  ApiTpkenss:
paths:
  /tasks:
    get:
      summary: Get a list of tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              example:
                - id: 1
                  title: Buy groceries
                - id: 2
                  title: Finish report
  /tasks/{taskId}:
    get:
      summary: Get a task by ID
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The requested task
          content:
            application/json:
              example:
                id: 1
                title: Buy groceries
